server:
    port: 8080
spring:
    main:
        banner-mode: off
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                -   id: item-service
                    uri: http://localhost:8903/item
                    predicates:
                        - Path=/item/**
                        - Method=GET,POST
                -   id: buyer-service
                    uri: http://localhost:8902/buyer
                    predicates:
                        - Path=/buyer/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8900/eureka/eureka
        fetch-registry: true