server:
    port: 8902
    servlet:
        context-path: /buyer

spring:
    main:
        banner-mode: off
    application:
        name: buyer-service
    datasource:
        url: jdbc:mysql://localhost:3306/emart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
    jpa:
        show-sql: true
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8900/eureka/eureka
        fetch-registry: true
        register-with-eureka: true

ribbon:
  eureka:
      enabled: true

#buyer-service:
#    ribbon:
#        listOfServers: http://localhost:8903