#debug: true
server:
    port: 8901
    servlet:
        context-path: /user

spring:
    application:
        name: user-service
    main:
        banner-mode: off
    datasource:
        url: jdbc:mysql://localhost:3306/emart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
    jpa:
        show-sql: true
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8900/eureka/eureka